# Ex2 - Getting and knowing your Data

### Step 1. Go to [Dataset_link](https://raw.githubusercontent.com/APSSDC-Data-Analysis/Data-Analysis-B3-Afternoon/master/D6_Preprocessing(29Aug2020)/titanic.csv)

* This dataset for Titanic passenger details
* Having columns are survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
* Some passengers were not found in their details (missing values are present)

## Step 2. Use the Csv file and assign it to a dataframe called titan_data

In [1]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/APSSDC-Data-Analysis/Data-Analysis-B3-Afternoon/master/D6_Preprocessing(29Aug2020)/titanic.csv")
data.head()

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      sex   age  sibsp  parch            ticket     fare cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

## Step 3. What is  the number of observations and entries in the dataset? 

In [11]:
data.shape

(891, 11)

## Step 4. Check the missing values and non-missing values  for every individual label

In [7]:
data.isnull().sum()

survived      0
pclass        0
name          0
sex           0
age         177
sibsp         0
parch         0
ticket        0
fare          0
cabin       687
embarked      2
dtype: int64

In [8]:
data.notnull().sum()

survived    891
pclass      891
name        891
sex         891
age         714
sibsp       891
parch       891
ticket      891
fare        891
cabin       204
embarked    889
dtype: int64

## Step 5. Replace missing values with mean value,If label having  numerics data and assign it to a new dataframe named as  titan_df

In [33]:
import numpy as np
titan_df = data.replace(to_replace = np.nan,value = data.mean())
titan_df.head()

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      sex   age  sibsp  parch            ticket     fare    cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500  B96 B98        S  
1  female  38.0      1      0          PC 17599  71.2833      C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250  B96 B98        S  
3  female  35.0      1      0            113803  53.1000     C123        S  
4    male  35.0      0      0            373450   8.0500  B96 B98        S

## Step 6. In titan_df, Replace missing values with mode value, if label having categorical data (object type) 

In [17]:
for column in titan_df.columns:
    titan_df[column].fillna(titan_df[column].mode()[0],inplace=True)

## Step 7. Now, check the missing values in titan_df

In [10]:
titan_df.isna().sum()

survived      0
pclass        0
name          0
sex           0
age           0
sibsp         0
parch         0
ticket        0
fare          0
cabin       687
embarked      2
dtype: int64

## Step 8. Finally, Export titan_df to "cleaned_titan_df.xlsx"

In [13]:
titan_df.to_excel("cleaned_titan_df.xlsx",encoding='utf-8')

# Task:
* Take same Dataset 
* Follow same steps by using Data imputation technique.
* Export final dataset to "cleaned_titan_df.csv"

In [4]:
from sklearn.impute import SimpleImputer

In [6]:
si = SimpleImputer(strategy = "mean")

In [7]:
g_data = data[["survived","age","fare"]]
g_data


survived   age     fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [8]:
si = SimpleImputer(strategy="mean")
si.fit_transform(g_data)

array([[ 0.        , 22.        ,  7.25      ],
       [ 1.        , 38.        , 71.2833    ],
       [ 1.        , 26.        ,  7.925     ],
       ...,
       [ 0.        , 29.69911765, 23.45      ],
       [ 1.        , 26.        , 30.        ],
       [ 0.        , 32.        ,  7.75      ]])

In [9]:
si = SimpleImputer(strategy="median")
si.fit_transform(g_data)

array([[ 0.    , 22.    ,  7.25  ],
       [ 1.    , 38.    , 71.2833],
       [ 1.    , 26.    ,  7.925 ],
       ...,
       [ 0.    , 28.    , 23.45  ],
       [ 1.    , 26.    , 30.    ],
       [ 0.    , 32.    ,  7.75  ]])

In [10]:
si = SimpleImputer(strategy="constant",fill_value=-1)
si.fit_transform(g_data)

array([[ 0.    , 22.    ,  7.25  ],
       [ 1.    , 38.    , 71.2833],
       [ 1.    , 26.    ,  7.925 ],
       ...,
       [ 0.    , -1.    , 23.45  ],
       [ 1.    , 26.    , 30.    ],
       [ 0.    , 32.    ,  7.75  ]])